services:
  server:
    build:
      context: ./apps/backend/
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend/:/apps/backend
    restart: always

  client:
    build:
      context: ./apps/frontend/
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend/:/apps/frontend
    restart: always


  nginx:
    container_name: node-note-nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/certs/:/etc/ssl/certs
      - ./nginx/private/:/etc/ssl/private
    depends_on:
      - server
      - client
    ports:
      - "80:80"
      - "443:443"
    restart: always
